active_model = "qwen"     # can be "gemini" or "qwen"
server_host = "127.0.0.1"
server_port = 8080

[gemini]
model = "gemini-robotics-er-1.5-preview"
api_base_url = "https://generativelanguage.googleapis.com"
api_version = "v1beta"
temperature = 0.5
thinking_budget = 0

[qwen]
model = "qwen3-vl:8b"
stream = false
